### ISSUE TITLE
Activity timings and duration issue

### ISSUE THREAD

**Issue by jafshin** [matsim-melbourne/demand#1]
While testing why example project with our input gets stuck at 1:00 am, I realised about 30% of all activities in our plan have start_time of `00:**:**`. First thing is that we don't need to provide start_time for activities, MATSim can estimate that (only the end time of the first activity is required).
Once removing the start times, it seems 3.6% of activities have end_time of `00:**:**`, I realised most of these early trips are other/rec trips, like this super active guy:
`
<person id="39">
  <plan selected="yes">
    <activity type="Home" x="323384" y="5814335" start_time="00:11:00" end_time="00:04:00"/>
    <leg mode="walk"/>
    <activity type="Other" x="324231" y="5814402" start_time="00:25:00" end_time="04:25:00"/>
    <leg mode="walk"/>
    <activity type="Shop" x="323706" y="5814445" start_time="06:18:00" end_time="06:02:00"/>
    <leg mode="walk"/>
    <activity type="Study" x="322616" y="5813570" start_time="06:15:00" end_time="14:15:00"/>
    <leg mode="walk"/>
    <activity type="Personal" x="323082" y="5812598" start_time="14:26:00" end_time="14:07:00"/>
    <leg mode="walk"/>
    <activity type="Study" x="324290" y="5814253" start_time="14:22:00" end_time="16:01:00"/>
    <leg mode="walk"/>
    <activity type="Shop" x="322650" y="5814877" start_time="20:08:00" end_time="20:04:00"/>
    <leg mode="walk"/>
    <activity type="Personal" x="322428" y="5814589" start_time="20:23:00" end_time="20:10:00"/>
    <leg mode="walk"/>
    <activity type="Shop" x="323004" y="5814608" start_time="20:24:00" end_time="20:35:00"/>
    <leg mode="walk"/>
    <activity type="Home" x="323384" y="5814335" start_time="21:00:00" end_time="23:56:00"/>
  </plan>
</person>`

Then there are cases that the length of an activity doesn't make much sense, like this shopping act that takes 13 hours:
`<person id="53">
  <plan selected="yes">
    <activity type="Home" x="323288" y="5813796" start_time="00:27:00" end_time="00:10:00"/>
    <leg mode="walk"/>
    <activity type="Shop" x="322505" y="5814324" start_time="00:22:00" end_time="13:32:00"/>
    <leg mode="walk"/>
    <activity type="Home" x="323288" y="5813796" start_time="13:48:00" end_time="23:37:00"/>
  </plan>
</person>`

Or this drop off that takes more than 15 hours:
`<person id="61">
  <plan selected="yes">
    <activity type="Home" x="323544" y="5813522" start_time="00:19:00" end_time="00:06:00"/>
    <leg mode="car"/>
    <activity type="Pickup/Dropoff/Deliver" x="331947" y="5803632" start_time="00:06:00" end_time="15:40:00"/>
    <leg mode="car"/>
    <activity type="Home" x="323544" y="5813522" start_time="15:55:00" end_time="23:40:00"/>
  </plan>
</person>`

I'll put together a comparison of timings with VISTA and will attach to this issue soon.

**Comment by dhixsingh** [comment]
@jafshin could you check the analyses graphs that are produced with the output? They should already give a lot of useful information with respect to how it compares to the input VISTA distributions. The times and durations are all drawn from distributions, so outliers are certainly possible, but I don't imagine you will/should find many of them.

**Comment by dhixsingh** [comment]
I can also see that in some instances the start/end time are swapped (ends before it starts), irrespective of whether MATSim needs it or not. I will fix that too. Irrespective of whether MATSim needs it or not, since the final CSV is still useful for other purposes outside of modelling in MATSim.

**Comment by jafshin** [comment]
Thanks @dhixsingh, yes the graphs were there, so good I didn't spend time re-creating them.

Okay, so I think I realised what the issue was. In VISTA we have trips with `ORIGPURP1="Unknown Purpose (at start of day)"`. This is usually for those who were not home at the beginning of the survey day (e.g. night shift workers, camped somewhere, etc.) The algorithm tags this as an "Other" activity and attaches a home activity before it and that is why we see so many Home to Other trips at the beginning of the day (which seems to overload the simulation as well). 

I manually fixed it and tested to run the model, it goes quickly to 5 am and gets stuck there - at least successfully passes the 1am! I will now look into the 5 am to see what is happening there. 

A suggestion to solve the "Unknown Purpose (at start of day)" issue is to use the ORIGPLACE1 column instead of ORIGPURP1 (or a combination of these two) and setting the algorithm to not to add a home activity at the beginning if the plan starts with this tag (let the chain to start from elsewhere).

**Comment by dhixsingh** [comment]
The above commits fix the poor time allocations issue, e.g, in `person 39` above.

**Comment by dhixsingh** [comment]
The fix for the excess `other` activities at the start of the day would be to simplify the "other" category as defined here:

https://github.com/matsim-melbourne/demand/blob/master/R/vista.R#L222

**Comment by dhixsingh** [comment]
The poor directions come from the fact that only start and end time distributions are currently tracked during plan generation so you could get really large or really small durations still. I made an attempt to do this but gave up since matching on start/end/duration was tricky. Needs more work. The code in question is here:

https://github.com/matsim-melbourne/demand/blob/master/R/plan.R#L92-L99

**Comment by dhixsingh** [comment]
Tracking the activity duration separately in #2.

**Comment by dhixsingh** [comment]
@jafshin the fix for all above but the durations issue (which I am tracking separately in #2) is in commit `25b1eb8` (note the branch). Things fixed include:

- Improved timing of activities (hopefully now none start before another finishes).
- Removed activity start time from MATSim XML output.
- Merged `Unknown Purpose (at start of day)` into the `Home` activity; `Other Purpose` and `Not Stated` are still treated as `Other`.

Could you try a 1% sample and see how that looks now?
