### ISSUE TITLE
Assigning start/end times to activities is taking too long

### ISSUE THREAD

**Issue by jafshin** [matsim-melbourne/demand#10]
Assigning start/end times to activities for a 10% sample (417,541 plans) takes ~58.5 hours to finish. Attached log file for more details
[makeExamplePopulation.log](https://github.com/matsim-melbourne/demand/files/5619200/makeExamplePopulation.log)

**Comment by dhixsingh** [comment]
@jafshin I've rewritten `time.R` in vectorised form and it is a lot faster now. Available in the `fix-time` branch now if you want to try it out.

**Comment by dhixsingh** [comment]
Getting different md5 hash on CI server, have accepted it for now:
```
MD5 ../actual/7.time/plan.csv: 370dc4fc052ad9087055abbc36661221
MD5 ../expected/7.time/plan.csv: b75cae5d342471f6ed6e861fc057af37

```

**Comment by dhixsingh** [comment]
Have implemented parallel times assignment which is much faster.
