### ISSUE TITLE
Fix broken analysis code and test

### ISSUE THREAD

**Issue by dhixsingh** [matsim-melbourne/demand#13]
The following code is disabled due to missing packages:
https://github.com/matsim-melbourne/demand/blob/c45f9bef9a1d884f14dfd6f0db00b505377c4979/R/makeExamplePopulation.R#L153-L157

As well, the following test is disabled as it crashes:
https://github.com/matsim-melbourne/demand/blob/c45f9bef9a1d884f14dfd6f0db00b505377c4979/tests/testthat/testLocateParallel.R#L11

**Comment by alanboth** [comment]
Hi Dhirendra,

Looks like it was due to the locateParallel code trying to select a mode for regions that don't exist. I've filtered the setup files to only use the SA1 regions present in the melbourne-2016-population-sample folder.

Regards,

Alan

**Comment by jafshin** [comment]
resolved in 4cd4d27b6edbfea4b5d5ab6baaf5d7064d704c25
