### ISSUE TITLE
Assigning coordinates to activities in SA1s taking too long

### ISSUE THREAD

**Issue by jafshin** [matsim-melbourne/demand#9]
Assigning coordinates to activities in SA1s for a 10% sample (417,541 plans) takes ~38 hours to finish. Attached log file for more details
[makeExamplePopulation.log](https://github.com/matsim-melbourne/demand/files/5619200/makeExamplePopulation.log)

**Comment by alanboth** [comment]
Fixed issue by making the locate stage parallel and optimising the code in [this commit](https://github.com/matsim-melbourne/demand/commit/96136e18de403b4bedf0b0bea3fcbc4bb1a50cf5)
